import { Bead, PresetDesign } from "./types";

// Real photoshoot beads — updated from BEADU FINAL LIST
export const INITIAL_BEADS: Bead[] = [
  {
    "id": "bead-final-001",
    "name": "Acrylic Evil Eye",
    "category": "acrylic",
    "price": 2,
    "material": "Premium Acrylic",
    "imageUrl": "/beads/final_beads/bead-final-001.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-002",
    "name": "Acrylic Round Rainbow",
    "category": "acrylic",
    "price": 5,
    "material": "Premium Acrylic",
    "imageUrl": "/beads/final_beads/bead-final-002.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-003",
    "name": "Holographic Tube",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-003.png",
    "isPremium": false,
    "rotationAllowed": true,
    "rotation": 90,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-004",
    "name": "Marble Blue",
    "category": "stone",
    "price": 5,
    "material": "Natural Stone",
    "imageUrl": "/beads/final_beads/bead-final-004.png",
    "isPremium": false,
    "rotationAllowed": true,
    "rotation": 90,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-005",
    "name": "Marble Green",
    "category": "stone",
    "price": 10,
    "material": "Natural Stone",
    "imageUrl": "/beads/final_beads/bead-final-005.png",
    "isPremium": true,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-006",
    "name": "Glass Holographic",
    "category": "glass",
    "price": 15,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-006.png",
    "isPremium": true,
    "rotationAllowed": true,
    "rotation": 90,
    "size": 2.12,
    "sizeMm": 17,
    "widthMm": 17,
    "active": true
  },
  {
    "id": "bead-final-007",
    "name": "Ebony Craft Bead",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-007.png",
    "isPremium": false,
    "rotationAllowed": true,
    "rotation": 90,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-008",
    "name": "Glass Holographic",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-008.png",
    "isPremium": false,
    "rotationAllowed": true,
    "rotation": 90,
    "size": 2.0,
    "sizeMm": 16,
    "widthMm": 16,
    "active": true
  },
  {
    "id": "bead-final-009",
    "name": "Candy Blue",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-009.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-010",
    "name": "Candy Dark Pink",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-010.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-011",
    "name": "Candy Green",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-011.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-012",
    "name": "Candy Orange",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-012.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-013",
    "name": "Candy Pink",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-013.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-014",
    "name": "Candy Round Blue",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-014.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-015",
    "name": "Candy Round Dark Pink",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-015.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-016",
    "name": "Candy Round Green",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-016.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-017",
    "name": "Candy Round Orange",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-017.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-018",
    "name": "Candy Round Pink",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-018.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-019",
    "name": "Candy Round Yellow",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-019.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-020",
    "name": "Candy Yellow",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-020.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-021",
    "name": "Raw Oval",
    "category": "stone",
    "price": 2,
    "material": "Natural Stone",
    "imageUrl": "/beads/final_beads/bead-final-021.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-022",
    "name": "Raw Round",
    "category": "stone",
    "price": 2,
    "material": "Natural Stone",
    "imageUrl": "/beads/final_beads/bead-final-022.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-023",
    "name": "Raw Square",
    "category": "stone",
    "price": 2,
    "material": "Natural Stone",
    "imageUrl": "/beads/final_beads/bead-final-023.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-024",
    "name": "Raw Tube",
    "category": "stone",
    "price": 2,
    "material": "Natural Stone",
    "imageUrl": "/beads/final_beads/bead-final-024.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-025",
    "name": "Glass Holographic",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-025.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-026",
    "name": "Wooden Round Blue",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-026.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-027",
    "name": "Wooden Round Pink",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-027.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-028",
    "name": "Wooden Round Dark Green",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-028.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-029",
    "name": "Glass Square Black",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-029.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-030",
    "name": "Glass Square Blue",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-030.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-031",
    "name": "Glass Square Green",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-031.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-032",
    "name": "Glass Square Yellow",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-032.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-033",
    "name": "Wooden Round Violet",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-033.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-034",
    "name": "Wooden Round Orange",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-034.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-035",
    "name": "Wooden Round Yellow",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-035.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-036",
    "name": "Glass Holographic",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-036.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-037",
    "name": "Marble Pink",
    "category": "stone",
    "price": 10,
    "material": "Natural Stone",
    "imageUrl": "/beads/final_beads/bead-final-037.png",
    "isPremium": true,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-038",
    "name": "Cat Eye Blue",
    "category": "crystal",
    "price": 5,
    "material": "Cat Eye Gemstone",
    "imageUrl": "/beads/final_beads/bead-final-038.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-039",
    "name": "Cat Eye Dark Blue",
    "category": "crystal",
    "price": 5,
    "material": "Cat Eye Gemstone",
    "imageUrl": "/beads/final_beads/bead-final-039.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-040",
    "name": "Cat Eye Green",
    "category": "crystal",
    "price": 5,
    "material": "Cat Eye Gemstone",
    "imageUrl": "/beads/final_beads/bead-final-040.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-041",
    "name": "Cat Eye Grey",
    "category": "crystal",
    "price": 5,
    "material": "Cat Eye Gemstone",
    "imageUrl": "/beads/final_beads/bead-final-041.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-042",
    "name": "Cat Eye Light Green",
    "category": "crystal",
    "price": 5,
    "material": "Cat Eye Gemstone",
    "imageUrl": "/beads/final_beads/bead-final-042.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-043",
    "name": "Cat Eye Pink",
    "category": "crystal",
    "price": 5,
    "material": "Cat Eye Gemstone",
    "imageUrl": "/beads/final_beads/bead-final-043.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-044",
    "name": "Holographic Square Black",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-044.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-045",
    "name": "Holographic Square Black",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-045.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 0.75,
    "sizeMm": 6,
    "widthMm": 6,
    "active": true
  },
  {
    "id": "bead-final-046",
    "name": "Glass Oval Black",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-046.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-047",
    "name": "Glass Round Matte Black",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-047.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-048",
    "name": "Glass Holographic",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-048.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-049",
    "name": "Palm Wood Bead",
    "category": "wood",
    "price": 10,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-049.png",
    "isPremium": true,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-050",
    "name": "Wooden Handcrafted",
    "category": "wood",
    "price": 5,
    "material": "Natural Wood",
    "imageUrl": "/beads/final_beads/bead-final-050.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.25,
    "sizeMm": 10,
    "widthMm": 10,
    "active": true
  },
  {
    "id": "bead-final-051",
    "name": "Breeze Bead",
    "category": "accent",
    "price": 5,
    "material": "Artisan Bead",
    "imageUrl": "/beads/final_beads/bead-final-051.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-052",
    "name": "Glass Oval White",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-052.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  },
  {
    "id": "bead-final-053",
    "name": "Glass Round Matte White",
    "category": "glass",
    "price": 5,
    "material": "Hand-Crafted Glass",
    "imageUrl": "/beads/final_beads/bead-final-053.png",
    "isPremium": false,
    "rotationAllowed": true,
    "size": 1.0,
    "sizeMm": 8,
    "widthMm": 8,
    "active": true
  }
];

export const PRESET_DESIGNS: PresetDesign[] = [
  {
    id: "marble-emerald",
    title: "Marble Emerald Elegance",
    subtitle: "Marble Green & Accent",
    price: 150,
    tag: "Bestseller",
    description: "Striking Marble Green spheres paired with Candy and Holographic accents.",
    wristInches: 7.0,
    cordType: "elastic",
    beadIds: [
      "bead-final-005",
      "bead-final-009",
      "bead-final-005",
      "bead-final-025",
      "bead-final-005",
      "bead-final-009",
      "bead-final-005",
    ],
    image: "/beads/final_beads/bead-final-005.png",
  },
  {
    id: "ocean-breeze",
    title: "Ocean Breeze & Wood",
    subtitle: "Wooden Round & Blue Marble",
    price: 120,
    tag: "Artisan Select",
    description: "Deep Marble Blue combined with Handcrafted Wooden beads.",
    wristInches: 7.5,
    cordType: "elastic",
    beadIds: [
      "bead-final-004",
      "bead-final-026",
      "bead-final-004",
      "bead-final-051",
      "bead-final-004",
      "bead-final-026",
      "bead-final-004",
    ],
    image: "/beads/final_beads/bead-final-004.png",
  },
  {
    id: "candy-pop",
    title: "Candy Pop Rainbow",
    subtitle: "Vibrant Candy & Acrylic",
    price: 90,
    tag: "Trending",
    description: "Playful colorful candy round beads with evil eye charm accents.",
    wristInches: 6.5,
    cordType: "elastic",
    beadIds: [
      "bead-final-009",
      "bead-final-010",
      "bead-final-011",
      "bead-final-001",
      "bead-final-012",
      "bead-final-013",
    ],
    image: "/beads/final_beads/bead-final-009.png",
  }
];
