import { Bead, PresetDesign } from "./types";

// Real photoshoot beads — 27 actual product photos processed to clean transparent PNGs
export const INITIAL_BEADS: Bead[] = [
  {
    id: "bead-batch-a-001",
    name: "Artisan Jade Green Sphere",
    category: "crystal",
    price: 0,
    material: "Natural Green Jade",
    imageUrl: "/beads/batch_a_clean/bead_001.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-002",
    name: "Frosted Ice Blue Cylinder",
    category: "crystal",
    price: 0,
    material: "Hand-Blown Glass",
    imageUrl: "/beads/batch_a_clean/bead_002.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1.25,
    sizeMm: 10,
    widthMm: 10,
    active: true,
  },
  {
    id: "bead-batch-a-003",
    name: "Terrazzo Mosaic Globe",
    category: "crystal",
    price: 0,
    material: "Artisan Terrazzo Glass",
    imageUrl: "/beads/batch_a_clean/bead_003.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-004",
    name: "Gilded Terracotta Sun Disc",
    category: "gold",
    price: 250,
    material: "Hand-Molded Terracotta & Gold Leaf",
    imageUrl: "/beads/batch_a_clean/bead_004.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.25,
    sizeMm: 10,
    widthMm: 10,
    active: true,
  },
  {
    id: "bead-batch-a-005",
    name: "Rose Quartz Heart Charm",
    category: "heart",
    price: 350,
    material: "Natural Rose Quartz",
    imageUrl: "/beads/batch_a_clean/bead_005.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.5,
    sizeMm: 12,
    widthMm: 12,
    active: true,
  },
  {
    id: "bead-batch-a-006",
    name: "Polished Indian Rosewood",
    category: "wood",
    price: 0,
    material: "Sustainably Sourced Rosewood",
    imageUrl: "/beads/batch_a_clean/bead_006.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-007",
    name: "Baroque Freshwater Pearl",
    category: "pearl",
    price: 0,
    material: "Natural Freshwater Pearl",
    imageUrl: "/beads/batch_a_clean/bead_007.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1.25,
    sizeMm: 10,
    widthMm: 10,
    active: true,
  },
  {
    id: "bead-batch-a-008",
    name: "Matte Obsidian Black Sphere",
    category: "crystal",
    price: 0,
    material: "Natural Black Obsidian",
    imageUrl: "/beads/batch_a_clean/bead_008.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-009",
    name: "Hand-Engraved Brass Emblem",
    category: "letter",
    price: 0,
    material: "Recycled Brass",
    imageUrl: "/beads/batch_a_clean/bead_009.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-010",
    name: "Ocean Blue Swirl Glass",
    category: "crystal",
    price: 0,
    material: "Artisanal Blown Glass",
    imageUrl: "/beads/batch_a_clean/bead_010.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-011",
    name: "Artisan Kundan Solstice Sun",
    category: "premium-charm",
    price: 450,
    material: "Solid Brass & Kundan Glass",
    imageUrl: "/beads/batch_a_clean/bead_011.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.5,
    sizeMm: 12,
    widthMm: 12,
    active: true,
  },
  {
    id: "bead-batch-a-012",
    name: "Raw Amethyst Gemstone",
    category: "crystal",
    price: 300,
    material: "Natural Indian Amethyst",
    imageUrl: "/beads/batch_a_clean/bead_012.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.13,
    sizeMm: 9,
    widthMm: 9,
    active: true,
  },
  {
    id: "bead-batch-a-013",
    name: "Golden Brass Spacer Bead",
    category: "gold",
    price: 0,
    material: "Polished Brass",
    imageUrl: "/beads/batch_a_clean/bead_013.png",
    isPremium: false,
    rotationAllowed: false,
    size: 0.75,
    sizeMm: 6,
    widthMm: 6,
    active: true,
  },
  {
    id: "bead-batch-a-014",
    name: "Midnight Lapis Lazuli",
    category: "crystal",
    price: 400,
    material: "Natural Lapis Lazuli",
    imageUrl: "/beads/batch_a_clean/bead_014.png",
    isPremium: true,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-015",
    name: "Emerald Cut Gemstone",
    category: "birthstone",
    price: 550,
    material: "Natural Emerald Gem",
    imageUrl: "/beads/batch_a_clean/bead_015.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.25,
    sizeMm: 10,
    widthMm: 10,
    active: true,
  },
  {
    id: "bead-batch-a-016",
    name: "Amber Honey Crystal",
    category: "crystal",
    price: 0,
    material: "Fired Baltic Amber",
    imageUrl: "/beads/batch_a_clean/bead_016.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-017",
    name: "Carved Wooden Mandala Disc",
    category: "zodiac",
    price: 0,
    material: "Hand-Carved Walnut Wood",
    imageUrl: "/beads/batch_a_clean/bead_017.png",
    isPremium: false,
    rotationAllowed: true,
    size: 1.25,
    sizeMm: 10,
    widthMm: 10,
    active: true,
  },
  {
    id: "bead-batch-a-018",
    name: "Copper Engraved Bar",
    category: "premium-charm",
    price: 350,
    material: "Recycled Copper",
    imageUrl: "/beads/batch_a_clean/bead_018.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.5,
    sizeMm: 12,
    widthMm: 12,
    active: true,
  },
  {
    id: "bead-batch-a-019",
    name: "Turquoise Pebble Charm",
    category: "crystal",
    price: 0,
    material: "Natural Turquoise",
    imageUrl: "/beads/batch_a_clean/bead_019.png",
    isPremium: false,
    rotationAllowed: true,
    size: 1.13,
    sizeMm: 9,
    widthMm: 9,
    active: true,
  },
  {
    id: "bead-batch-a-020",
    name: "Ruby Oval Pendant",
    category: "birthstone",
    price: 650,
    material: "Gold-Plated Natural Ruby",
    imageUrl: "/beads/batch_a_clean/bead_020.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.5,
    sizeMm: 12,
    widthMm: 12,
    active: true,
  },
  {
    id: "bead-batch-a-021",
    name: "Silver Hammered Sphere",
    category: "silver",
    price: 0,
    material: "925 Sterling Silver",
    imageUrl: "/beads/batch_a_clean/bead_021.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-022",
    name: "Faceted Sapphire Gem",
    category: "birthstone",
    price: 600,
    material: "Natural Sapphire Stone",
    imageUrl: "/beads/batch_a_clean/bead_022.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.25,
    sizeMm: 10,
    widthMm: 10,
    active: true,
  },
  {
    id: "bead-batch-a-023",
    name: "Artisan Ceramic Speckle",
    category: "ceramic",
    price: 0,
    material: "Glazed Stoneware Clay",
    imageUrl: "/beads/batch_a_clean/bead_023.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-024",
    name: "Zodiac Celestial Sun",
    category: "zodiac",
    price: 0,
    material: "Hand-Carved Brass Disc",
    imageUrl: "/beads/batch_a_clean/bead_024.png",
    isPremium: false,
    rotationAllowed: true,
    size: 1.13,
    sizeMm: 9,
    widthMm: 9,
    active: true,
  },
  {
    id: "bead-batch-a-025",
    name: "Golden Heart Spacer",
    category: "heart",
    price: 200,
    material: "18K Gold Plated Brass",
    imageUrl: "/beads/batch_a_clean/bead_025.png",
    isPremium: true,
    rotationAllowed: true,
    size: 1.25,
    sizeMm: 10,
    widthMm: 10,
    active: true,
  },
  {
    id: "bead-batch-a-026",
    name: "Smoky Quartz Crystal",
    category: "crystal",
    price: 0,
    material: "Natural Smoky Quartz",
    imageUrl: "/beads/batch_a_clean/bead_026.png",
    isPremium: false,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
  {
    id: "bead-batch-a-027",
    name: "White Opal Sphere",
    category: "pearl",
    price: 300,
    material: "Ethically Mined Opal",
    imageUrl: "/beads/batch_a_clean/bead_027.png",
    isPremium: true,
    rotationAllowed: false,
    size: 1,
    sizeMm: 8,
    widthMm: 8,
    active: true,
  },
];

export const PRESET_DESIGNS: PresetDesign[] = [
  {
    id: "earth-cats-eye",
    title: "Earth & Jade Harmony",
    subtitle: "Jade Spheres & Rosewood",
    price: 600,
    tag: "Most Popular",
    description: "Natural green jade spheres alternating with polished Indian rosewood beads on elastic cord.",
    wristInches: 7.0,
    cordType: "elastic",
    beadIds: [
      "bead-batch-a-001",
      "bead-batch-a-006",
      "bead-batch-a-001",
      "bead-batch-a-006",
      "bead-batch-a-005",
      "bead-batch-a-006",
      "bead-batch-a-001",
      "bead-batch-a-006",
      "bead-batch-a-001",
    ],
    image: "/beads/pomelli_photoshoot_image_1_1_0726.png",
  },
  {
    id: "ocean-blue",
    title: "Ocean Blue & Pearl",
    subtitle: "Hand-Blown Glass & Pearl",
    price: 550,
    tag: "Artisan Select",
    description: "Swirling ocean blue glass with baroque freshwater pearls and an obsidian sphere.",
    wristInches: 7.5,
    cordType: "elastic",
    beadIds: [
      "bead-batch-a-010",
      "bead-batch-a-007",
      "bead-batch-a-010",
      "bead-batch-a-008",
      "bead-batch-a-010",
      "bead-batch-a-007",
      "bead-batch-a-010",
    ],
    image: "/beads/pomelli_photoshoot_image_9_16_0726 (2).png",
  },
  {
    id: "kundan-solstice",
    title: "Kundan Solstice Gold",
    subtitle: "Gold Disc & Artisan Brass",
    price: 1000,
    tag: "High Jewelry",
    description: "Gilded terracotta sun discs with a Kundan Solstice centerpiece and golden brass spacers.",
    wristInches: 7.0,
    cordType: "elastic",
    beadIds: [
      "bead-batch-a-013",
      "bead-batch-a-004",
      "bead-batch-a-013",
      "bead-batch-a-011",
      "bead-batch-a-013",
      "bead-batch-a-004",
      "bead-batch-a-013",
    ],
    image: "/beads/pomelli_photoshoot_image_9_16_0726 (5).png",
  },
  {
    id: "zodiac-mandala",
    title: "Zodiac Mandala Soul",
    subtitle: "Carved Wood & Turquoise",
    price: 800,
    tag: "Personalized",
    description: "Hand-carved walnut mandala discs paired with natural turquoise pebbles and amber crystals.",
    wristInches: 6.5,
    cordType: "elastic",
    beadIds: [
      "bead-batch-a-017",
      "bead-batch-a-019",
      "bead-batch-a-017",
      "bead-batch-a-016",
      "bead-batch-a-017",
      "bead-batch-a-019",
    ],
    image: "/beads/pomelli_photoshoot_image_9_16_0726.png",
  },
];
